# Generated by Django 5.0.1 on 2024-10-21 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
